server:
  port: 80
spring:
  freemarker:
    charset: UTF-8
    content-type: text/html
    suffix: .ftl
    template-loader-path: classpath:/templates
    cache: false
    allow-request-override: true
    allow-session-override: true
    check-template-location: true
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/bottom?characterEncoding=utf8&useSSL=false&useUnicode=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: true
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: admin
#    password: 123456